### PR TITLE
Portfolio template site

### PR DESCRIPTION
**Pull request by murbar**

### CODE REVIEW

**Comment by murbar** [comment]
That completes the MVP, I believe.

**Comment by murbar** [comment]
I set to publish on Pages but it looks like only the master branch can be served up. It should go live after merge.

**Comment by sabrinagear** [comment]
Okay I'll merge

**Comment by sabrinagear** [comment]
Actually, I want to see what you are talking about so I can relay it.
Please bring yo on the stand-up.

**Pull request merged**
